---
on:
  - pull_request
  - push

name: security

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  analyze:
    name: Analyze
    permissions:
      contents: read
    uses: ./.github/workflows/security.yml
    with:
      audit-inputs: .github actions
    secrets:
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
