name: composer-require-checker

on:
  workflow_call:
    inputs:
      command-options:
        description: Options for the Composer Require Checker tool.
        default:
        required: false
        type: string
      composer-command:
        description: Composer command to run.
        default: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
        required: false
        type: string
      composer-version:
        description: Composer version to use.
        default:
        required: false
        type: string
      concurrency-group:
        description: Concurrency group name.
        default: ${{ github.workflow }}-${{ github.ref }}
        required: false
        type: string
      enable-concurrency:
        description: Enable concurrency.
        default: true
        required: false
        type: boolean
      extensions:
        description: List of extensions to PHP.
        default:
        required: false
        type: string
      os:
        description: Operating systems to test, separated by comma.
        default: '["ubuntu-latest"]'
        required: false
        type: string
      php-ini-values:
        description: Initial values for PHP configuration.
        default: date.timezone='UTC'
        required: false
        type: string
      php-version:
        description: PHP versions to test, separated by comma.
        default: '["8.4"]'
        required: false
        type: string
      tools:
        description: Tools to test, separated by comma.
        default:
        required: false
        type: string

    secrets:
      AUTH_TOKEN:
        description: GitHub token for composer.
        required: false

jobs:
  composer-require-checker:
    name: PHP ${{ matrix.php-version }}-${{ matrix.os }}

    concurrency:
      group:  ${{ matrix.os }}-${{ matrix.php-version }}-${{ inputs.concurrency-group }}
      cancel-in-progress: ${{ inputs.enable-concurrency }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.os) }}
        php-version: ${{ fromJson(inputs.php-version) }}

    steps:
      - name: Checkout.
        uses: actions/checkout@v5

      - name: Setup PHP Environment.
        uses: php-forge/actions/actions/php-setup@main
        with:
          auth-token: ${{ secrets.AUTH_TOKEN }}
          composer-command: ${{ inputs.composer-command }}
          composer-version: ${{ inputs.composer-version }}
          coverage-driver: none
          extensions: ${{ inputs.extensions }}
          ini-values: ${{ inputs.php-ini-values }}
          php-version: ${{ matrix.php-version }}
          tools: ${{ inputs.tools }}

      - name: Check composer requirements.
        run: vendor/bin/composer-require-checker ${{ inputs.command-options }}
