name: infection

on:
  workflow_call:
    inputs:
      command:
        description: Command to run.
        default: infection
        required: false
        type: string
      command-options:
        description: Options for the infection tool.
        default: --threads=2 --ignore-msi-with-no-mutations --only-covered
        required: false
        type: string
      composer-command:
        description: Composer command to run.
        default: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
        required: false
        type: string
      composer-version:
        description: Composer version to use.
        default:
        required: false
        type: string
      coverage:
        description: Generate code coverage report.
        default: pcov
        required: false
        type: string
      debug:
        description: Debug mode.
        default: false
        required: false
        type: boolean
      development:
        description: Run in development mode.
        default: false
        required: false
        type: boolean
      extensions:
        description: List of extensions to PHP.
        default:
        required: false
        type: string
      framework-options:
        description: Options for the framework.
        default:
        required: false
        type: string
      ini-values:
        description: Initial values for PHP configuration.
        default: date.timezone='UTC'
        required: false
        type: string
      os:
        description: Os to test, separated by comma.
        default: '["ubuntu-latest"]'
        required: false
        type: string
      php:
        description: PHP versions to test, separated by comma.
        default: '["8.4"]'
        required: false
        type: string
      phpstan:
        description: Run PHPStan and use it with Infection.
        default: false
        required: false
        type: boolean
      phpstan-configuration:
        description: PHPStan configuration file.
        default: phpstan.neon
        required: false
        type: string
      tools:
        description: Tools to test, separated by comma.
        default:
        required: false
        type: string
    secrets:
      AUTH_TOKEN:
        description: GitHub token for composer.
        required: false
      STRYKER_DASHBOARD_API_KEY:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  infection:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.os) }}
        php: ${{ fromJson(inputs.php) }}

    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Install PHP.
        uses: shivammathur/setup-php@v2
        with:
          coverage: ${{ inputs.coverage }}
          extensions: ${{ inputs.extensions}}
          ini-values: ${{ inputs.ini-values}}
          php-version: ${{ matrix.php }}
          tools: ${{ inputs.tools }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update composer.
        run: composer self-update ${{ inputs.composer-version }}

      - name: Configure composer.
        run: |
          if [ "${{ secrets.AUTH_TOKEN }}" != '' ]; then
            composer config -g github-oauth.github.com ${{ secrets.AUTH_TOKEN }};
          fi
          if [ "${{ inputs.development }}" = 'true' ]; then
            composer require --dev infection/infection:dev-master --prefer-dist --no-interaction --no-progress;
          fi

      - name: Install dependencies with composer.
        run: ${{ inputs.composer-command }}

      - name: Cache PHPStan results.
        if: ${{ inputs.phpstan }}
        uses: actions/cache@v4
        with:
          path: .phpstan/cache
          key: phpstan-${{ runner.os }}-${{ hashFiles('phpstan.neon*') }}
          restore-keys: |
            phpstan-${{ runner.os }}-

      - name: Run PHPStan (build cache).
        if: ${{ inputs.phpstan }}
        run: vendor/bin/phpstan --configuration=${{ inputs.phpstan-configuration }} analyse

      - name: Run infection.
        run: |
          vendor/bin/${{ inputs.command }} ${{ inputs.command-options }} ${{ inputs.phpstan && '--static-analysis-tool=phpstan' || '' }} ${{ inputs.framework-options }}
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

      - name: Archive infection results.
        if: ${{ inputs.debug }}
        uses: actions/upload-artifact@v4
        with:
          name: infection-${{ matrix.php }}-${{ matrix.os }}
          path: ./infection.log

      - name: Download all workflow run artifacts.
        if: ${{ inputs.debug }}
        uses: actions/download-artifact@v4
