---
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

name: linter

jobs:
  super-linter:
    uses: php-forge/actions/.github/workflows/reusable-linter.yml@feature-2
    secrets:
      AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
