---
on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "CHANGELOG.md"
      - ".gitignore"
      - ".gitattributes"

  push:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "CHANGELOG.md"
      - ".gitignore"
      - ".gitattributes"

name: linter

jobs:
  linter:
    uses: php-forge/actions/.github/workflows/reusable-linter.yml@main
    secrets:
      AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
