name: phpunit

on:
  workflow_call:
    inputs:
      concurrency-group:
        description: Concurrency group name.
        default: ${{ github.workflow }}-${{ github.ref }}
        required: false
        type: string
      composer-command:
        description: Composer command to run.
        default: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
        required: false
        type: string
      composer-version:
        description: Composer version to use.
        default:
        required: false
        type: string
      coverage:
        description: Generate code coverage report.
        default: pcov
        required: false
        type: string
      debug:
        description: Display warnings in phpunit.
        default:
        required: false
        type: string
      enable-concurrency:
        description: Enable concurrency.
        default: true
        required: false
        type: boolean
      exclude-group-phpunit:
        description: Exclude group from phpunit.
        default:
        required: false
        type: string
      extensions:
        description: List of extensions to PHP.
        default:
        required: false
        type: string
      ini-values:
        description: Initial values for PHP configuration.
        default: date.timezone='UTC'
        required: false
        type: string
      os:
        description: Os to test, separated by comma.
        default: '["ubuntu-latest","windows-latest"]'
        required: false
        type: string
      php:
        description: PHP versions to test, separated by comma.
        default: '["8.1","8.2","8.3","8.4"]'
        required: false
        type: string
      tools:
        description: Tools to test, separated by comma.
        default:
        required: false
        type: string

    secrets:
      AUTH_TOKEN:
        description: GitHub token for composer.
        required: false
      CODECOV_TOKEN:
        description: Codecov token.
        required: false

jobs:
  phpunit:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    concurrency:
      group:  ${{ matrix.os }}-${{ matrix.php }}-${{ inputs.concurrency-group }}
      cancel-in-progress: ${{ inputs.enable-concurrency }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.os) }}
        php: ${{ fromJson(inputs.php) }}

    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Install PHP.
        uses: shivammathur/setup-php@v2
        with:
          coverage: ${{ inputs.coverage }}
          extensions: ${{ inputs.extensions }}
          ini-values: ${{ inputs.ini-values }}
          php-version: ${{ matrix.php }}
          tools: ${{ inputs.tools }}

      - name: Update composer.
        run: composer self-update ${{ inputs.composer-version }}

      - name: Configure composer on linux.
        if: matrix.os == 'ubuntu-latest'
        run: |
          if [ "${{ secrets.AUTH_TOKEN }}" != '' ]; then
            composer config -g github-oauth.github.com ${{ secrets.AUTH_TOKEN }};
          fi

      - name: Configure composer on windows.
        if: matrix.os == 'windows-latest'
        run: |
          if ($env:AUTH_TOKEN -ne '') {
            composer config -g github-oauth.github.com $env:AUTH_TOKEN
          }
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

      - name: Install dependencies with composer.
        run: ${{ inputs.composer-command }}

      - name: Run tests on linux with phpunit and generate coverage.
        if: matrix.os == 'ubuntu-latest'
        run: |
          PHPUNIT_CMD="vendor/bin/phpunit --coverage-clover=coverage.xml --colors=always"

          if [ -n "${{ inputs.group-phpunit }}" ]; then
            PHPUNIT_CMD="$PHPUNIT_CMD --group ${{ inputs.group-phpunit }}"
          fi

          if [ -n "${{ inputs.exclude-group-phpunit }}" ]; then
            PHPUNIT_CMD="$PHPUNIT_CMD --exclude-group ${{ inputs.exclude-group-phpunit }}"
          fi

          if [ -n "${{ inputs.debug }}" ]; then
            PHPUNIT_CMD="$PHPUNIT_CMD ${{ inputs.debug }}"
          fi

          eval "$PHPUNIT_CMD"

      - name: Run tests on windows with phpunit and generate coverage.
        if: matrix.os == 'windows-latest'
        run: |
          $phpunitCmd = "vendor/bin/phpunit --coverage-clover=coverage.xml --colors=always"

          if ($env:GROUP) {
            $phpunitCmd += " --group $env:GROUP"
          }

          if ($env:EXCLUDE_GROUP) {
            $phpunitCmd += " --exclude-group $env:EXCLUDE_GROUP"
          }

          if ($env:DEBUG_FLAG) {
            $phpunitCmd += " $env:DEBUG_FLAG"
          }

          Invoke-Expression $phpunitCmd
        env:
          GROUP: ${{ inputs.group-phpunit }}
          EXCLUDE_GROUP: ${{ inputs.exclude-group-phpunit }}
          DEBUG_FLAG: ${{ inputs.debug }}


      - name: Upload coverage to Codecov.
        if: matrix.php == '8.1'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
