name: phpunit

on:
  workflow_call:
    inputs:
      composer-command:
        description: Composer command to run.
        default: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
        required: false
        type: string
      composer-version:
        description: Composer version to use.
        default:
        required: false
        type: string
      concurrency-group:
        description: Concurrency group name.
        default: ${{ github.workflow }}-${{ github.ref }}
        required: false
        type: string
      coverage:
        description: Generate code coverage report.
        default: pcov
        required: false
        type: string
      coverage-driver:
        description: Code coverage driver to use (pcov, xdebug).
        default: pcov
        required: false
        type: string
      coverage-file:
        description: Coverage output file name.
        default: coverage.xml
        required: false
        type: string
      coverage-format:
        description: Coverage report format (clover, html, xml).
        default: clover
        required: false
        type: string
      enable-concurrency:
        description: Enable concurrency.
        default: true
        required: false
        type: boolean
      extensions:
        description: List of extensions to PHP.
        default:
        required: false
        type: string
      os:
        description: Os to test, separated by comma.
        default: '["ubuntu-latest","windows-latest"]'
        required: false
        type: string
      phpunit-configuration:
        description: PHPUnit configuration file.
        default: ""
        required: false
        type: string
      phpunit-debug:
        description: Display warnings in phpunit.
        default: ""
        required: false
        type: string
      phpunit-exclude-group:
        description: Exclude group from phpunit.
        default:
        required: false
        type: string
      phpunit-group:
        description: Include specific group in phpunit.
        default:
        required: false
        type: string
      phpunit-path:
        description: Path to PHPUnit executable.
        default: vendor/bin/phpunit
        required: false
        type: string
      phpunit-test-suite:
        description: Specific test suite to run.
        default: ""
        required: false
        type: string
      php-ini-values:
        description: Initial values for PHP configuration.
        default: date.timezone='UTC'
        required: false
        type: string
      php-version:
        description: PHP versions to test, separated by comma.
        default: '["8.1","8.2","8.3","8.4"]'
        required: false
        type: string
      tools:
        description: Tools to test, separated by comma.
        default:
        required: false
        type: string

    secrets:
      AUTH_TOKEN:
        description: GitHub token for composer.
        required: false
      CODECOV_TOKEN:
        description: Codecov token.
        required: false

jobs:
  phpunit:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    concurrency:
      group:  ${{ matrix.os }}-${{ matrix.php }}-${{ inputs.concurrency-group }}
      cancel-in-progress: ${{ inputs.enable-concurrency }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.os) }}
        php: ${{ fromJson(inputs.php) }}

    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Setup PHP Environment.
        uses: php-forge/actions/actions/php-setup@main
        with:
          auth-token: ${{ secrets.AUTH_TOKEN }}
          composer-command: ${{ inputs.composer-command }}
          composer-version: ${{ inputs.composer-version }}
          coverage-driver: ${{ inputs.coverage-driver }}
          extensions: ${{ inputs.extensions }}
          ini-values: ${{ inputs.php-ini-values }}
          php-version: ${{ matrix.php-version }}
          tools: ${{ inputs.tools }}

      - name: Run PHPUnit tests with coverage.
        uses: php-forge/actions/actions/phpunit@main
        with:
          configuration: ${{ inputs.phpunit-configuration }}
          coverage-file: ${{ inputs.coverage-file }}
          coverage-format: ${{ inputs.coverage-format }}
          coverage-token: ${{ secrets.CODECOV_TOKEN }}
          coverage: ${{ inputs.coverage }}
          debug: ${{ inputs.phpunit-debug }}
          exclude-group: ${{ inputs.phpunit-exclude-group }}
          group: ${{ inputs.phpunit-group }}
          path: ${{ inputs.phpunit-path }}
          test-suite: ${{ inputs.phpunit-test-suite }}
