---
name: linter

on:
  workflow_call:
    inputs:
      checkout_fetch_depth:
        description: Fetch depth for checkout action.
        default: 0
        required: false
        type: number
      concurrency-group:
        description: Concurrency group name.
        default: linter/${{ github.workflow }}-${{ github.ref }}
        required: false
        type: string
      enable-concurrency:
        description: Enable concurrency.
        default: true
        required: false
        type: boolean
      os:
        description: OS runner as a JSON array string '["ubuntu-latest"]'.
        default: '["ubuntu-latest"]'
        required: false
        type: string
      validate-microsoft-rules:
        description: Enable natural language linting (textlint + Microsoft rules).
        default: false
        required: false
        type: boolean

    secrets:
      AUTH_TOKEN:
        description: GitHub token.
        required: true

jobs:
  lint:
    concurrency:
      cancel-in-progress: ${{ inputs.enable-concurrency }}
      group: ${{ inputs.concurrency-group }}

    name: Super Linter

    permissions:
      checks: write
      contents: read
      statuses: write

    runs-on: ${{ fromJSON(inputs.os) }}

    steps:
      - name: Checkout.
        uses: actions/checkout@v5
        with:
          fetch-depth: ${{ inputs.checkout_fetch_depth }}

      - name: Install Microsoft textlint rules
        if: ${{ inputs.validate-microsoft-rules }}
        run: npm install -g @textlint/textlint-rule-preset-microsoft

      - name: Run super linter.
        uses: super-linter/super-linter/slim@v8.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
          VALIDATE_CHECKOV: ${{ env.VALIDATE_CHECKOV || 'false' }}
          VALIDATE_ENV: ${{ env.VALIDATE_ENV || 'false' }}
          VALIDATE_GIT_MERGE_CONFLICT_MARKERS: >-
            ${{ env.VALIDATE_GIT_MERGE_CONFLICT_MARKERS || 'false' }}
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: >-
            ${{ env.VALIDATE_GITHUB_ACTIONS_ZIZMOR || 'false' }}
          VALIDATE_JSCPD: ${{ env.VALIDATE_JSCPD || 'false' }}
          VALIDATE_TRIVY: ${{ env.VALIDATE_TRIVY || 'false' }}
